### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by unknown-user397** [TeamMoegMC/TheWinterRescue#60]
### Error Behaviour

![modpack bug2](https://user-images.githubusercontent.com/109055080/210160817-e1d187e1-9ff3-474c-bdbd-2e43e892393e.png)
![modpack bug](https://user-images.githubusercontent.com/109055080/210160828-4c96642a-c1f5-4bd4-8af9-24f1030bb8da.png)

### Expected Behaviour

i wanted the stack of coal to stay the same in the clay vessel

### Reproduce

every time i put more than one coal and exit of the UI for the clay vessel. it gives me back one piece of coal

### Modpack version

0.5.5-rc3-hf3

**Comment by khjxiaogu** [comment]
Can not reproduce, can you explain further?

**Comment by Corfiot** [comment]
https://youtu.be/1fx4JBE0Tfw

put clay vessel in hotbar
rightclick
pickup stack of coal, right click in center 4 times
press ESC
richtclick
only 3 or sometimes 2 coal is there or just one

>> coal lost

same if pressing E instead of ESC to close interface
this interface really needs a live counter of how much fuel is necessary as opposed to how much in inserted like the hover popup

**Comment by khjxiaogu** [comment]
Fixed, please update to the latest build.
